---
- name: install nginx and monit
  become: yes
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx
    - monit
  notify:
    - enable service
  tags: deploy
  
- name: config monit
  become: yes
  blockinfile:
    path: /etc/monit/monitrc
    block: |
      set httpd port 2812 and
      use address localhost
      allow localhost
      allow devops:test
      
      check process nginx with pidfile /run/nginx.pid
         start program = "/usr/sbin/service nginx start"
         stop program = "/usr/sbin/service nginx stop"
  notify:
    - restart monit
  tags: deploy
  
- name: delete link
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags: deploy

- name: add monit config
  become: yes
  template:
    src: templates/monit.conf
    dest: /etc/nginx/sites-available/monit.conf
  tags: deploy
  
- name: link config
  become: yes
  file:
    src: /etc/nginx/sites-available/monit.conf
    dest: /etc/nginx/sites-enabled/monit.conf
    state: link
  notify:
    - restart nginx
  tags: deploy
