---
- name: install nginx and monit
  become: yes
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx
    - monit
  notify:
    - enable service
  tags: deploy
